---
all:
  children:
    load_balancer:
      hosts:
        lb-server:
          ansible_host: "{{ lb_public_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          server_type: load_balancer
          nginx_config: nginx-lb.conf
          ports:
            - 80
            - 443
            - 22

    app_servers:
      hosts:
        app-server-1:
          ansible_host: "{{ app_server_1_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: application
          instance_id: 1
          ports:
            - 8000
            - 22
        app-server-2:
          ansible_host: "{{ app_server_2_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: application
          instance_id: 2
          ports:
            - 8000
            - 22
        app-server-3:
          ansible_host: "{{ app_server_3_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: application
          instance_id: 3
          ports:
            - 8000
            - 22

    databases:
      hosts:
        redis-server:
          ansible_host: "{{ redis_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: redis
          ports:
            - 6379
            - 22
        postgres-server:
          ansible_host: "{{ postgres_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: postgres
          ports:
            - 5432
            - 22
        mongo-server:
          ansible_host: "{{ mongo_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: mongodb
          ports:
            - 27017
            - 22

    celery_services:
      hosts:
        celery-worker:
          ansible_host: "{{ celery_worker_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: celery_worker
          ports:
            - 22
        celery-beat:
          ansible_host: "{{ celery_beat_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: celery_beat
          ports:
            - 22
        celery-flower:
          ansible_host: "{{ celery_flower_private_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ key_file_path }} -W %h:%p {{ app_user }}@{{ bastion_public_ip }}"'
          server_type: celery_flower
          ports:
            - 5555
            - 22

    bastion:
      hosts:
        bastion-server:
          ansible_host: "{{ bastion_public_ip }}"
          ansible_user: "{{ app_user }}"
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          server_type: bastion
          ports:
            - 22 