import logging
import random
import time

from sqlalchemy import update, select, func, text
# from sqlalchemy.future import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.config import settings
from app.db.sql.models import URL
# from sqlalchemy.sql import func, text

logger = logging.getLogger(__name__)

class URLKeyRepository:

    @staticmethod
    def _generate_key():
        return ''.join(random.choices(settings.key_charset, k=settings.key_length))
    
    @staticmethod
    async def get_unused_key(session: AsyncSession):
        """
        Atomically acquire an unused key using SELECT FOR UPDATE SKIP LOCKED.
        This prevents race conditions in distributed systems.
        """
        try:
            result = await session.execute(
                select(URL)
                .where(~URL.is_used)
                .limit(1)
                .with_for_update(skip_locked=True)  # Key fix for race conditions!
            )
            url = result.scalars().first()

            if url is not None:
                # Mark the key as used
                await session.execute(
                    update(URL)
                    .where(URL.id == url.id)
                    .values(is_used=True)
                )
                await session.commit()
                logger.info(f"Acquired key: {url.key}")
                return url
            else:
                logger.warning("No unused keys available")
                return None

        except Exception as e:
            await session.rollback()
            logger.error(f"Error acquiring unused key: {e}")
            raise
    
    @staticmethod
    async def get_unused_key_raw(session: AsyncSession) -> dict | None:
        """
        Raw SQL version - use if ORM becomes a bottleneck.
        Benchmark before switching!
        """

        result = await session.execute(
            text("""
                UPDATE urls 
                SET is_used = true 
                WHERE id = (
                    SELECT id FROM urls 
                    WHERE is_used = false 
                    LIMIT 1 
                    FOR UPDATE SKIP LOCKED
                )
                RETURNING id, key
            """)
        )
        row = result.first()
        
        if row:
            await session.commit()
            return {"id": row[0], "key": row[1]}
        return None

    # ========================================================================
    # OPTIMIZATION STRATEGY 1: PostgreSQL generate_series (FASTEST)
    # ========================================================================
    @staticmethod
    async def pre_populate_keys_postgres_native(
        session: AsyncSession, 
        count: int = 100000
    ) -> int:
        """
        Use PostgreSQL's generate_series to create keys directly in the database.
        This is the FASTEST method - O(1) operation from application perspective.
        
        Performance: ~100K keys in 1-2 seconds
        
        Trade-off: Keys are generated by PostgreSQL, not Python.
        Uses a simple sequential approach with random salt.
        """
        try:
            if count <= 0:
                return 0

            result = await session.execute(
                text("""
                    INSERT INTO urls (key, is_used)
                    SELECT 
                        -- Generate 7 random alphanumeric characters
                        array_to_string(
                            ARRAY(
                                SELECT substr('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789', 
                                    (random() * 61 + 1)::int, 1)
                                FROM generate_series(1, 7)
                            ),
                            ''
                        ) as key,
                        false as is_used
                    FROM generate_series(1, :count)
                    ON CONFLICT (key) DO NOTHING
                    RETURNING id
                """),
                {"count": count}
            )
            
            inserted_count = len(result.fetchall())
            await session.commit()
            
            logger.info(f"Pre-populated {inserted_count} keys using PostgreSQL native method")
            return inserted_count

        except Exception as e:
            await session.rollback()
            logger.error(f"Error pre-populating keys: {e}")
            raise
        
        
    # ========================================================================
    # OPTIMIZATION STRATEGY 2: Single INSERT with VALUES (Very Fast)
    # ========================================================================
    @staticmethod
    async def pre_populate_keys_single_insert(
        session: AsyncSession, 
        count: int = 100000
    ) -> int:
        """
        Generate all keys in Python, then insert with a SINGLE SQL query.
        
        Performance: ~100K keys in 2-3 seconds
        
        Pros: 
        - Only one database round-trip
        - Full control over key generation
        - PostgreSQL can optimize the entire insert
        
        Cons:
        - Large SQL query string (but PostgreSQL handles it well)
        - Limited by max_allowed_packet (default: 1GB, more than enough)
        """
        try:
            if count <= 0:
                return 0

            # Pre-generate all keys
            keys = [URLKeyRepository._generate_key() for _ in range(count)]
            
            # Build single VALUES clause
            # Use proper SQL escaping
            values_clause = ",".join([f"('{key}', false)" for key in keys])
            
            query = text(f"""
                INSERT INTO urls (key, is_used) 
                VALUES {values_clause}
                ON CONFLICT (key) DO NOTHING
                RETURNING id
            """)
            
            result = await session.execute(query)
            inserted_count = len(result.fetchall())
            await session.commit()
            
            logger.info(f"Pre-populated {inserted_count} keys using single INSERT")
            return inserted_count

        except Exception as e:
            await session.rollback()
            logger.error(f"Error pre-populating keys: {e}")
            raise


    # ========================================================================
    # OPTIMIZATION STRATEGY 3: COPY (Absolute Fastest for Huge Datasets)
    # ========================================================================
    @staticmethod
    async def pre_populate_keys_copy(
        session: AsyncSession, 
        count: int = 100000
    ) -> int:
        """
        Use PostgreSQL COPY command for maximum performance.
        
        Performance: ~100K keys in 0.5-1 second
        
        This is the fastest method for large datasets.
        PostgreSQL's COPY bypasses most overhead.
        
        Note: Requires raw asyncpg connection (not SQLAlchemy's abstraction)
        """
        try:
            if count <= 0:
                return 0

            # Generate keys
            keys = [URLKeyRepository._generate_key() for _ in range(count)]
            
            # Get raw asyncpg connection from SQLAlchemy
            raw_conn = await session.connection()
            asyncpg_conn = raw_conn.connection.driver_connection
            
            # Create CSV-like data in memory
            data = "\n".join([f"{key}\tf" for key in keys]).encode('utf-8')
            
            # Use COPY command
            await asyncpg_conn.copy_to_table(
                'urls',
                source=data,
                columns=['key', 'is_used'],
                format='csv'
            )
            
            await session.commit()
            
            logger.info(f"Pre-populated {count} keys using COPY command")
            return count

        except Exception as e:
            await session.rollback()
            logger.error(f"Error pre-populating keys with COPY: {e}")
            raise

    # ========================================================================
    # OPTIMIZATION STRATEGY 4: Batch with executemany (Balanced)
    # ========================================================================
    @staticmethod
    async def pre_populate_keys_executemany(
        session: AsyncSession, 
        count: int = 100000,
        batch_size: int = 10000
    ) -> int:
        """
        Use SQLAlchemy's executemany with proper batching.
        
        Performance: ~100K keys in 3-4 seconds
        
        Pros:
        - Good balance of speed and safety
        - Uses parameterized queries (prevents SQL injection)
        - Respects batch_size for memory control
        
        This is the RECOMMENDED method for most use cases.
        """
        try:
            if count <= 0:
                return 0

            # Generate all keys at once (fast in Python)
            keys = [URLKeyRepository._generate_key() for _ in range(count)]
            
            inserted_count = 0
            
            # Process in batches
            for i in range(0, len(keys), batch_size):
                batch = keys[i:i + batch_size]
                
                # Use executemany with parameterized query
                query = text("""
                    INSERT INTO urls (key, is_used) 
                    VALUES (:key, false)
                    ON CONFLICT (key) DO NOTHING
                """)
                
                # Create parameter list
                params = [{"key": key} for key in batch]
                
                # Execute batch
                await session.execute(query, params)
                inserted_count += len(batch)
                
                # Log progress for large inserts
                if i % (batch_size * 10) == 0 and i > 0:
                    logger.info(f"Progress: {i}/{count} keys inserted")
            
            await session.commit()
            
            logger.info(f"Pre-populated {inserted_count} keys using executemany")
            return inserted_count

        except Exception as e:
            await session.rollback()
            logger.error(f"Error pre-populating keys: {e}")
            raise

    # ========================================================================
    # OPTIMIZATION STRATEGY 5: Hybrid Approach (Production Ready)
    # ========================================================================
    @staticmethod
    async def pre_populate_keys_hybrid(
        session: AsyncSession, 
        count: int = 100000
    ) -> int:
        """
        Production-ready hybrid approach.
        Automatically chooses the best method based on count.
        
        - Small batches (<1K): Use executemany (safe, fast enough)
        - Medium batches (1K-50K): Use single INSERT (fast, memory efficient)
        - Large batches (>50K): Use PostgreSQL native (fastest)
        
        This gives you the best performance across all scenarios.
        """
        try:
            if count <= 0:
                return 0

            # Choose strategy based on count
            if count < 1000:
                # For small batches, safety and simplicity matter more
                return await URLKeyRepository.pre_populate_keys_executemany(
                    session, count, batch_size=500
                )
            elif count < 50000:
                # For medium batches, single INSERT is optimal
                return await URLKeyRepository.pre_populate_keys_single_insert(
                    session, count
                )
            else:
                # For large batches, use PostgreSQL native
                return await URLKeyRepository.pre_populate_keys_postgres_native(
                    session, count
                )

        except Exception as e:
            await session.rollback()
            logger.error(f"Error pre-populating keys: {e}")
            raise

    @staticmethod
    async def pre_populate_keys(session: AsyncSession, count: int = 100000):
        """
        Pre-populate the database with unused keys.
        Uses efficient bulk insertion with parameterized queries.
        
        Args:
            session: AsyncSession - The database session
            count: int - Number of keys to pre-populate (default: 100000)
        
        Returns:
            int: Number of keys successfully inserted
        """
        try:
            # Generate keys efficiently - collision probability is negligible
            # With 62^7 possibilities and 100K keys, collision chance < 0.0001%
            if count <= 0:
                logger.info("Key pre-population count is zero or negative, skipping.")
                return 0

            keys = [URLKeyRepository._generate_key() for _ in range(count)]
            
            # Use larger batches for better performance
            batch_size = settings.key_batch_size
            
            for i in range(0, len(keys), batch_size):
                batch = keys[i:i + batch_size]
                await URLKeyRepository._bulk_insert_keys_optimized(session, batch, commit=False)
            
            # Single commit at the end for maximum efficiency
            await session.commit()
            
            logger.info(f"Pre-populated {count} keys")
            return count

        except Exception as e:
            await session.rollback()
            logger.error(f"Error pre-populating keys: {e}")
            raise

    @staticmethod
    async def _bulk_insert_keys(session: AsyncSession, keys: list[str]) -> int:
        """
        Bulk insert with raw SQL for better performance.
        This IS worth optimizing with raw SQL.
        """
        if not keys:
            return 0
        
        # Use raw SQL for bulk insert - much faster than ORM
        values = ", ".join([f"('{key}', false)" for key in keys])
        query = text(f"""
            INSERT INTO urls (key, is_used) 
            VALUES {values}
            ON CONFLICT (key) DO NOTHING
        """)
        
        result = await session.execute(query)
        await session.commit()
        
        return result.rowcount  # type: ignore[attr-defined]

    @staticmethod
    async def _bulk_insert_keys_optimized(session: AsyncSession, keys: list[str], commit: bool = True):
        """
        Optimized bulk insert using parameterized queries.
        Much safer and often faster than string concatenation.
        """
        if not keys:
            return
        
        # Use parameterized query for safety and performance
        # PostgreSQL handles this very efficiently
        query = text("""
            INSERT INTO urls (key, is_used) 
            VALUES (:key, false)
            ON CONFLICT (key) DO NOTHING
        """)
        
        # Bulk execute with parameters
        key_params = [{"key": key} for key in keys]
        await session.execute(query, key_params)
        
        if commit:
            await session.commit()

    @staticmethod
    async def get_available_key_count(session: AsyncSession) -> int:
        """Get count of available unused keys."""
        try:
            result = await session.execute(
                select(func.count(URL.id)).where(~URL.is_used)
            )
            count = result.scalar()
            return count or 0
        except Exception as e:
            logger.error(f"Error getting available key count: {e}")
            return 0

    @staticmethod
    async def get_total_key_count(session: AsyncSession) -> int:
        """Get total count of keys."""
        try:
            result = await session.execute(
                select(func.count(URL.id))
            )
            count = result.scalar()
            return count or 0
        except Exception as e:
            logger.error(f"Error getting total key count: {e}")
            return 0
        
    # ========================================================================
    # BENCHMARK HELPER
    # ========================================================================
    @staticmethod
    async def benchmark_insert_methods(session: AsyncSession, count: int = 10000):
        """
        Benchmark all insertion methods.
        Useful for finding the best method for your specific setup.
        """
        
        methods = [
            ("PostgreSQL Native", URLKeyRepository.pre_populate_keys_postgres_native),
            ("Single INSERT", URLKeyRepository.pre_populate_keys_single_insert),
            ("Executemany", URLKeyRepository.pre_populate_keys_executemany),
            ("Hybrid Approach", URLKeyRepository.pre_populate_keys_hybrid),
            ("Regular Bulk Insert", URLKeyRepository.pre_populate_keys),
            # ("COPY Command", URLKeyRepository.pre_populate_keys_copy),
            
        ]
        
        results = {}
        
        for name, method in methods:
            # Clean up before benchmark
            await session.execute(text("DELETE FROM urls"))
            await session.commit()
            
            start = time.time()
            inserted = await method(session, count)
            duration = time.time() - start
            
            results[name] = {
                "duration": duration,
                "keys_per_second": inserted / duration if duration > 0 else 0,
                "inserted": inserted
            }
            
            logger.info(f"{name}: {inserted} keys in {duration:.2f}s ({results[name]['keys_per_second']:.0f} keys/s)")
        
        return results